// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfuVsK2vWXqcVRyibvydXx9gPs1kZm8Nk',
    appId: '1:864553671196:web:219a45f4bfa271a7ec5dd9',
    messagingSenderId: '864553671196',
    projectId: 'chatapp-74bf7',
    authDomain: 'chatapp-74bf7.firebaseapp.com',
    storageBucket: 'chatapp-74bf7.firebasestorage.app',
    measurementId: 'G-Y0ZJWLYX5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJIPwiFQqyCs_rnI0p70u_MMWjpG9_VDE',
    appId: '1:864553671196:android:38bb94b085ac5d54ec5dd9',
    messagingSenderId: '864553671196',
    projectId: 'chatapp-74bf7',
    storageBucket: 'chatapp-74bf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCBSHnOReV9xkfA3_r-yX7P7e5Sfg9RqM',
    appId: '1:864553671196:ios:ceb016fdae6aa16aec5dd9',
    messagingSenderId: '864553671196',
    projectId: 'chatapp-74bf7',
    storageBucket: 'chatapp-74bf7.firebasestorage.app',
    iosBundleId: 'openmobilecode.appAnimation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCBSHnOReV9xkfA3_r-yX7P7e5Sfg9RqM',
    appId: '1:864553671196:ios:ceb016fdae6aa16aec5dd9',
    messagingSenderId: '864553671196',
    projectId: 'chatapp-74bf7',
    storageBucket: 'chatapp-74bf7.firebasestorage.app',
    iosBundleId: 'openmobilecode.appAnimation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfuVsK2vWXqcVRyibvydXx9gPs1kZm8Nk',
    appId: '1:864553671196:web:075ff620584f10d6ec5dd9',
    messagingSenderId: '864553671196',
    projectId: 'chatapp-74bf7',
    authDomain: 'chatapp-74bf7.firebaseapp.com',
    storageBucket: 'chatapp-74bf7.firebasestorage.app',
    measurementId: 'G-700QWWBBGR',
  );
}
